// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdwMWEmQ_8_xksx7RCDOuL9IJwifEEYd8',
    appId: '1:419862673797:android:2b37bfacf947d4e4606cec',
    messagingSenderId: '419862673797',
    projectId: 'alivedemo-1b6bb',
    storageBucket: 'alivedemo-1b6bb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDevxHydkyAmyUd-PlfMyYmZ3c28nzctuo',
    appId: '1:419862673797:ios:254cbdd26948e345606cec',
    messagingSenderId: '419862673797',
    projectId: 'alivedemo-1b6bb',
    storageBucket: 'alivedemo-1b6bb.firebasestorage.app',
    androidClientId: '419862673797-7ijeerch4k0043vkel7m4744iva7bukq.apps.googleusercontent.com',
    iosClientId: '419862673797-gbg7oq0q06fivqsm2vmbf3jcat723h1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.aliveDemo',
  );
}
